INSERT INTO `Exercice`(`Terrain`, `Type`, `LevelID`, `Description`)
VALUES
-- //Prelude
 ("Pente facile.", 0, 3, "Le skieur exécute quatre (4) virages chasse-neige."),
 ("Pente facile.", 2, 3, "Exécuter le pas escalier."),
 ("Pente facile.", 2, 3, "Exécuter le pas de ciseaux."),
 ("Pente facile.", 2, 3, "Exécuter l'exercice chasse-neige."),
 ("Pente facile.", 2, 3, "Taper sur la neige avec le ski intérieur au virage en effectuant un virage chasse-neige."),
 ("Pente facile.", 2, 3, "Pouvoir tomber et se relever sans assistance."),
 ("Aucune.", 2, 3, "Pouvoir monter avec ses bâtons dans une remontée mécanique puis en débarquer, seul ou avec une autre personne, mais sans assistance"),
-- //Christiania
("Pente facile.", 0, 6, "Le skieur exécute au moins une partie du virage en tournant les skis en position parallèle (quatre (4) virages)."),
("Section de pente abrupte.", 2, 6, "Exécuter un dérapage."),
("Section de pente abrupte.", 2, 6, "Exécuter un dérapage diagonal pendant une traversée."),
("Pente facile.", 2, 6, "Exécuter un dérapage arrondi."),
("Pente facile.", 2, 6, "Arrêt 'hockey'."),
("Pente facile.", 2, 6, "Descendre sur un ski en levant l'autre sur une distance d'au moins cinq (5) mètres."),
("Pente facile.", 2, 6, "Exécuter, en descendant, des pas de patineur tout en suivant la ligne de pente. "),
-- //Parallele 1
("Pente facile.", 0, 7, "Le skieur exécute des virages parallèles avec planté de bâton. Il peut prendre un appui chasse-neige avant le déclenchement de chaque virage (virages stems-parallèles)."),
("Pente facile.", 2, 7, "Exécuter une traversée et planter le bâton du côté aval à plusieurs reprises, le tout accompagné de flexions et d’extensions."),
("Pente facile.", 2, 7, "Exécuter un virage amont par flexion/extension, à partir de la ligne de pente avec planté de bâton coordonné et synchronisé avec le déclenchement du virage."),
("Pente facile.", 2, 7, "En descendant, exécuter une série de petits sauts en soulevant les skis et en les changeant de direction à chaque saut."),
("Pente facile.", 2, 7, "Exécuter des virages sur le ski extérieur.Le ski intérieur au virage doit être complètement soulevé de la neige pendant au moins une partie du virage."),
-- //Paralele 2
("Pente facile.", 0, 8, "Le skieur exécute des virages parallèles par flexion-extension tout en contrôlant sa vitesse. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de chaque virage."),
("Pente facile.", 2, 8, "Exécuter une traversée en effectuant des flexions-extensions avec transfert de poids du ski aval au ski amont (L'équilibriste)"),
("Pente facile.", 2, 8, "Exécuter des virages parallèles en amorçant chaque virage par un petit saut."),
("Pente facile.", 2, 8, "À partir de la ligne de pente, exécuter un virage amont par flexion-extension avec transfert de poids. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement du virage."),
("Pente facile.", 2, 8, "Exécuter des virages surle sommet des bosses. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de chaque virage. "),
("Pente facile.", 2, 8, "Exécuter des changements de direction avec flexions-extensions dynamiques (exercice de pivot). "),
("Pente facile.", 2, 8, "Exécuter des virages sur le ski extérieur. Le ski intérieur doit être soulevéde laneige tout au long du virage."),
-- //Competence 1
("Pente difficile.", 0, 9, "Le skieur exécute des virages à court rayon par flexion-extension (découpage progressif). Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de chaque virage."),
("Pente difficile.", 0, 9, "Le skieur exécute des virages à long rayon par flexion/extension (découpage progressif).Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de chaque virage."),
("Pente difficile.", 2, 9, "Exécuter le pas parallèle."),
("Pente difficile.", 2, 9, "À partir de la ligne de pente, exécuter un virage amont par flexion-extension avec transfert de poids et mise à carres par angulation. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement du virage."),
("Pente facile.", 2, 9, "Exécuter des changements de direction avec flexions-extensions dynamiques et plantés de bâtons (exercice de pivot)."),
("Pente difficile avec bosses.", 2, 9, "Absorber au moins quatre (4) bosses en ligne droite."),
("Pente facile.", 2, 9, "Exécuter le pas Charleston sans planté de bâton (phase initiale)"),
("Pente facile bien lisse.", 2, 9, "Exécuter un arrêt aval"),
-- //Competence 2
("Pente difficile.", 0, 10, "Le skieur exécute des virages à court rayon (découpage progressif). Il doit maitriser la techniqued'anticipation (ouverture des épaules vers l'extérieur du virage)."),
("Pente difficile.", 0, 10, "Le skieur exécute des virages à long rayon (découpage progressif).Il doit dissocier l’alignement du haut et du bas du corps."),
("Pente difficile.", 2, 10, "Exécuter trois (3) pas de patineuren se dirigeant vers l'amont. Choix de terrain."),
("Pente difficile.", 2, 10, "A partir de la ligne de pente, exécuter un virage amont (découpage progressif) avec transfert de poids et mise àcarres par angulation tout en découpant le virage (virage arrêt)."),
("Pente facile.", 2, 10, "Exécuter des virages de type stem-parallèle (pas convergent) sans planté de bâton avec flexion/extension et transfert de poids."),
("Aucune", 2, 10, "Chasse-neige dynamique en insistant sur la flexion/extension."),
("Pente difficile avec bosses.", 2, 10, "Exécuter des virages àlong rayon dans un champ de bosses.(Optionel)"),
("Pente facile.", 2, 10, "Exécuter une partie du virage sur le ski intérieur (quatre (4) virages)"),
("Pente facile.", 2, 10, "Exécuter au moins quatre (4) changements de direction sur le même ski."),
-- //Élite 1
("Pente très difficile.", 0, 11, "Le skieur exécute des virages à court rayon (découpage progressif) tout en maîtrisant la technique d'anticipation. Il peut changersa ligne de descente s'il le désire, mais il doit enchaîner au moins trois virages en succession."),
("Pente très difficile.", 0, 11, "Exécuter des virages à long rayon (découpage progressif) tout en maîtrisant la technique d'anticipation et encontrôlant sa vitesse."),
("Pente facile.", 2, 11, "En descente, exécuter une série de petits sauts en soulevant les skis et en les changeant de direction à chaque saut. Le bâton doit être planté de façon coordonnée àchaque changement de direction (au moins six (6) changements de direction). "),
("Pente facile.", 2, 11, "Découpage continu:Chasse-neige «béquille».Le skieur prend position, un ski mis à carre de façon marquée (ski extérieur au virage), un ski à plat.Le ski mis à carre conduit sans décrocher, le ski à plat glisse sur la neige.Le skieur exécute un virage à vitesse lente et s’immobilise en remontant la pente.Exécuter des deux côtés."),
("Pente facile.", 2, 11, "Découpage continu:Le «crabe» Le skieur prend position en ligne de pente, un ski mis à carre de façon marquée, un ski à plat.Le skieur se déplace de façon diagonale dans la pente sans tourner (les épaules demeurent face au bas de la pente).Il enchaîne les changements de directions en alternant les mises à carres."),
("Pente facile", 2, 11, "Chasse-neige dynamique en insistant sur la flexion/extension et le transfert de poids."),
("Pente difficile.", 2, 11, "Exercice contre-rotationsans planté de bâton"),
("Pente difficile avec bosses.", 2, 11, "Le skieur exécute des virages à court rayon (découpage progressif) dans les bosses à vitesse régulière.(Optionel)"),
("Pente facile.", 2, 11, "Exécuter des virages sur le ski intérieur. Le ski extérieur doit être soulevéde laneige tout au long du virage. "),
("Pente facile.", 2, 11, "Exécuter au moins quatre (4) virages sur le même ski."),
-- //Élite 2
("Pente très difficile.", 0, 12, "Le skieur exécute des virages à court rayon (découpage progressif) en contrôlant sa vitesseet en conservant toujours le même rayon àses virages sans changer sa ligne de descente. Il doit maîtriser la technique d'anticipation, la mise àcarres par angulation et le transfert de poids."),
("Pente facile.", 0, 12, "Exécuter desvirages à long rayon (découpage continu) tout en contrôlant sa vitesse. Le skieur doit maîtriser la technique d'anticipation, la mise àcarres par angulation et le transfert de poids. "),
("Pente difficile.", 2, 12, "Exécuter le pas tournant du patineur (step up)."),
("Pente facile.", 2, 12, "En descente, exécuter une série de petits sauts en soulevant les skis eten les changeant de direction à chaque saut. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de l'extension et les skis doivent être soulevés àégale distance du sol (au moins six (6) changements de direction). "),
("Pente facile.", 2, 12, "Découpage continu : Virages à long rayon àvitesse rapide sur la carre intérieure du skiextérieur au virage, ski intérieur soulevéen position convergente."),
("Pente facile", 2, 12, "Chasse-neige dynamique en insistant sur la flexion/extension, le transfert de poids et la séparation du haut et du bas du corps."),
("Pente difficile.", 2, 12, "Exercice contre-rotation : Le skieur traverse diagonalement la pente et pivote les skis vers l'amont alors que le haut du corps tourne rapidement vers l'aval (allègement par flexion pour faciliter le pivot des skis vers l'amont). La contre-rotation est d'abord amorcée par les pieds. Le skieur effectue cette manoeuvre àplusieurs reprises pendant la traversée. Il utilise le planté de bâton du côté amont pour déclencher chaque pivot et plante le bâton du côté aval à l'arrêt de la flexion."),
("Pente très difficile avec bosses.", 2, 12, "Exécuter des virages à long rayon (découpage progressif) dans un champ de bosses.  (Optionel)"),
("Pente facile.", 2, 12, "Exécuter Le pas Charleston avec planté de bâton (phase avancée)."),
("Pente difficile.", 2, 12, "Exécuter au moins quatre (4) virages sur le même ski."),
-- //Excellence
("Pente très difficile.", 0, 13, "Le skieur exécute des virages à court rayon (découpage progressif) en contrôlant sa vitesse et conservant toujours le même rayon àses virages sans changer sa ligne de descente. Il doit maîtriser la technique d'anticipation, la mise àcarres par angulation et le transfert de poids.De plus, le skieur doit bien découper les virages. Il doit exécuterles mouvements dans la bonne séquence et avec aisance."),
("Pente difficile.", 0, 13, "Exécuter des virages à long rayon (découpage continu) àvitesse rapide (virages slalom géant). Le skieur doit maîtriser la technique d'anticipation, la mise àcarres par angulation et le transfert depoids. De plus, il doit bien découper les virages. Les mouvements doivent être exécutés dans la bonne séquence et avec aisance."),
("Pente très difficile.", 2, 13, "Le skieur exécute des virages à court rayon (découpage progressif) avec forte prise de carres (arrêt brusque de la flexion). Il doit dissocier l'alignement du haut et du bas du corps et maîtriser la mise à carres par angulation et le transfert de poids. De plus, il doit bien découper les virages."),
("Pente facile.", 2, 13, "Exécuter tout en descendant, une série de petits sauts d'un ski àl'autre avec changements de direction. Lorsque le ski droit touche la neige après un pivot vers la gauche, le ski gauche se trouve soulevé et vice versa. Le planté de bâton doit être coordonné et synchronisé avec le déclenchement de l'extension (au moins six (6) changements de direction)."),
("Pente difficile.", 2, 13, "Découpage continu : Le skieur exécute des virages à court rayon."),
("Pente facile", 2, 13, "Chasse-neige dynamique en insistant sur la flexion/extension, le transfert de poids, la séparation du haut et du bas du corps et le découpage (découpage progressif)."),
("Pente difficile.", 2, 13, "Exercice contre-rotation : Le skieur traverse diagonalement la pente et pivote les skis vers l'amont alors que le haut du corps tourne rapidement vers l'aval (allègement par flexion pour faciliter le pivot des skis vers l'amont). La contre-rotation est d'abord amorcée par les pieds. Le skieur effectuecette manoeuvre àplusieurs reprises pendant la traversée. Il plante le bâton du côté amont pour déclencher chaque pivot et plante le bâton du côté aval à l'arrêt de la flexion. Les skis décrivent un arc découpé (découpage progressif) àchaquemouvement de contre-rotation."),
("Pente très difficile avec bosses.", 2, 13, "Le skieur exécute des virages à court rayon (découpage progressif) dans les bosses, en appliquant leprincipe d'avalement, en contrôlant sa vitesseet en conservant toujours le même rayon àses virages sans changer sa ligne de descente. Il doit maîtriser la technique d'anticipation, la mise àcarres par angulation et le transfert depoids. De plus, il doit bien découper chaque virage. (Optionel)"),
